/**
 * GBO Entities
 * It allows the possibility of standardizing the way entities are created and generated for the different regions and global entities of GBO, allowing the creation of entities in a single way for the different users with a new way that allows this action to be carried out. 
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: dario.vega@gruposantander.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.kie.kogito.hr.rest.client;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.ws.rs.*;
import jakarta.ws.rs.core.Response;

import org.eclipse.microprofile.rest.client.annotation.RegisterProvider;
import org.eclipse.microprofile.rest.client.inject.RegisterRestClient;

/**
 * GBO Entities
 *
 * <p>
 * It allows the possibility of standardizing the way entities are created and
 * generated for the different regions and global entities of GBO, allowing the
 * creation of entities in a single way for the different users with a new way
 * that allows this action to be carried out.
 *
 */

@ApplicationScoped
@RegisterRestClient(configKey = "dummy-rest-service")
@Path("/dummy")
public interface DummyRestClient {

    /**
     * Retrieves operational entities.
     *
     * Retrieves operational entities filtering by GLCS (Global Limit Code System).
     *
     */
    @GET
    @Produces({ "application/json" })
    Response getDummy();

}
