---
app:
  image: docker.io/jizuzquiza/kogito-dmn-test-project:1.0.0
  livenessProbe:
    failureThreshold: 10
    httpGet:
      path: /q/health/live
      scheme: HTTP
    initialDelaySeconds: 30
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 40
  ports:
    http: 8080
  readinessProbe:
    failureThreshold: 10
    httpGet:
      path: /q/health/ready
      scheme: HTTP
    initialDelaySeconds: 30
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 40
  startupProbe:
    failureThreshold: 10
    httpGet:
      path: /q/health/started
      scheme: HTTP
    initialDelaySeconds: 20
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 40
